COLOR_MODEL = "RGB"

BOX_COLOR_NAME = "BOXCOLOR"
BOX_COLOR_RGB = (0, 0, 255) # BLUE


TEXT_COLOR_NAME = "TEXTCOLOR"
TEXT_COLOR_RGB = (255, 0, 0) # RED

BOX_TEXT_COLOR_NAME = "BOXTEXTCOLOR"
BOX_TEXT_COLOR_RGB = (255, 0, 255) # PURPLE

PAGE_COLOR_NAME = "PAGECOLOR"
PAGE_COLOR_RGB = (0, 0, 0) # BLACK